"""Add facility column to Patient

Revision ID: 0d9f11631270
Revises: bcf32a0cdc92
Create Date: 2022-11-09 21:04:54.962923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9f11631270'
down_revision = 'bcf32a0cdc92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lg_patient', sa.Column('facility', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lg_patient', 'facility')
    # ### end Alembic commands ###
