"""fix one to many relationship

Revision ID: 0fead9f59065
Revises: 6572c727b1b2
Create Date: 2022-11-14 20:29:42.895479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fead9f59065'
down_revision = '6572c727b1b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lg_patient_checkups_fkey', 'lg_patient', type_='foreignkey')
    op.drop_column('lg_patient', 'checkups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lg_patient', sa.Column('checkups', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('lg_patient_checkups_fkey', 'lg_patient', 'lg_checkup', ['checkups'], ['id'])
    # ### end Alembic commands ###
