"""Add age & full_name to patient table

Revision ID: 26af920c6095
Revises: 9db9319746ad
Create Date: 2022-10-29 15:47:43.895271

"""
from alembic import op
import sqlalchemy as sa
from app.patient.models import Patient


# revision identifiers, used by Alembic.
revision = "26af920c6095"
down_revision = "9db9319746ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
