"""change Checkup table column name

Revision ID: 6572c727b1b2
Revises: b3174e6ddae6
Create Date: 2022-11-14 20:02:12.343399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6572c727b1b2'
down_revision = 'b3174e6ddae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lg_checkup', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('lg_checkup', 'checkup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lg_checkup', sa.Column('checkup', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('lg_checkup', 'data')
    # ### end Alembic commands ###
