"""Add Checkup table

Revision ID: a5733e9421fc
Revises: 0d9f11631270
Create Date: 2022-11-09 22:00:50.564635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5733e9421fc'
down_revision = '0d9f11631270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
