"""Add Checkup table

Revision ID: aea670104593
Revises: a5733e9421fc
Create Date: 2022-11-09 22:01:40.231729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aea670104593'
down_revision = 'a5733e9421fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lg_checkup',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('checkup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['lg_patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lg_checkup')
    # ### end Alembic commands ###
