"""user-patient one to many

Revision ID: b3174e6ddae6
Revises: aea670104593
Create Date: 2022-11-10 19:08:33.848287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b3174e6ddae6"
down_revision = "aea670104593"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lg_patient", sa.Column("checkups", postgresql.UUID(as_uuid=True)))
    op.create_foreign_key(None, "lg_patient", "lg_checkup", ["checkups"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lg_patient", type_="foreignkey")
    op.drop_column("lg_patient", "checkups")
    # ### end Alembic commands ###
