"""Change Column name

Revision ID: c7a5ec80a2ea
Revises: a2b5c4beac44
Create Date: 2022-10-29 22:24:28.091258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c7a5ec80a2ea"
down_revision = "a2b5c4beac44"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lg_patient", sa.Column("recorder_id", postgresql.UUID(as_uuid=True)))
    op.drop_constraint("lg_patient_user_id_fkey", "lg_patient", type_="foreignkey")
    op.create_foreign_key(None, "lg_patient", "lg_user", ["recorder_id"], ["id"])
    op.drop_column("lg_patient", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lg_patient",
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "lg_patient", type_="foreignkey")
    op.create_foreign_key(
        "lg_patient_user_id_fkey", "lg_patient", "lg_user", ["user_id"], ["id"]
    )
    op.drop_column("lg_patient", "recorder_id")
    # ### end Alembic commands ###
