"""empty message

Revision ID: ee32cd7f1d5a
Revises: e76b87973b80
Create Date: 2022-10-29 15:27:10.084013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee32cd7f1d5a'
down_revision = 'e76b87973b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lg_user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('lg_user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lg_user', 'updated_at')
    op.drop_column('lg_user', 'created_at')
    # ### end Alembic commands ###
